import { Reem_Kufi } from "next/font/google";
import "./globals.css";

// Load the Reem Kufi font
const reemKufi = Reem_Kufi({
  variable: "--font-reem-kufi",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${reemKufi.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
